[package]
name = "filigram-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9"
indicatif = "0.17"
image = "0.24"
imageproc = "0.23"
log = "0.4"
rayon = "1.5"
rusttype = "0.9"
walkdir = "2.3"
